
/* File generated by gen_cfile.py. Should not be modified. */

#include "Ds402_Slave.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
unsigned short  Controlword = 0x0;		/* Mapped at index 0x6040, subindex 0x00 */
UNS16 Statusword = 0x0;		/* Mapped at index 0x6041, subindex 0x00 */
INTEGER8 Modes_of_operation = 0x0;		/* Mapped at index 0x6060, subindex 0x00 */
INTEGER8 Modes_of_operation_display = 0x0;		/* Mapped at index 0x6061, subindex 0x00 */
INTEGER32 Position_demannd_value = 0x0;		/* Mapped at index 0x6062, subindex 0x00 */
INTEGER32 Position_actual_value = 0x0;		/* Mapped at index 0x6064, subindex 0x00 */
UNS32 Maximal_following_error = 0x0;		/* Mapped at index 0x6065, subindex 0x00 */
UNS32 Position_window = 0x0;		/* Mapped at index 0x6067, subindex 0x00 */
UNS16 Position_window_time = 0x0;		/* Mapped at index 0x6068, subindex 0x00 */
INTEGER32 Velocity_sensor_actual_value = 0x0;		/* Mapped at index 0x6069, subindex 0x00 */
INTEGER32 Velocity_demand_value = 0x0;		/* Mapped at index 0x606B, subindex 0x00 */
INTEGER32 Velocity_actual_value = 0x0;		/* Mapped at index 0x606C, subindex 0x00 */
INTEGER16 Current_actual_value = 0x0;		/* Mapped at index 0x6078, subindex 0x00 */
INTEGER32 Target_position = 0x0;		/* Mapped at index 0x607A, subindex 0x00 */
INTEGER32 Home_offset = 0x0;		/* Mapped at index 0x607C, subindex 0x00 */
INTEGER32 Software_position_limit_Minimal_position_limit = 0x0;		/* Mapped at index 0x607D, subindex 0x01 */
INTEGER32 Software_position_limit_Maximal_position_limit = 0x0;		/* Mapped at index 0x607D, subindex 0x02 */
UNS32 Maximal_profile_velocity = 0x0;		/* Mapped at index 0x607F, subindex 0x00 */
UNS32 Profile_velocity = 0x0;		/* Mapped at index 0x6081, subindex 0x00 */
UNS32 Profile_acceleration = 0x0;		/* Mapped at index 0x6083, subindex 0x00 */
UNS32 Profile_deceleration = 0x0;		/* Mapped at index 0x6084, subindex 0x00 */
UNS32 Quick_stop_deceleration = 0x0;		/* Mapped at index 0x6085, subindex 0x00 */
INTEGER16 Motion_profile_type = 0x0;		/* Mapped at index 0x6086, subindex 0x00 */
INTEGER8 Position_notation_index = 0x0;		/* Mapped at index 0x6089, subindex 0x00 */
REAL32 Position_dimention_index = 0.000000;		/* Mapped at index 0x608A, subindex 0x00 */
INTEGER8 Velocity_notation_index = 0x0;		/* Mapped at index 0x608B, subindex 0x00 */
REAL32 Velocity_dimention_index = 0.000000;		/* Mapped at index 0x608C, subindex 0x00 */
INTEGER8 Acceleraion_notation_index = 0x0;		/* Mapped at index 0x608D, subindex 0x00 */
REAL32 Acceleraion_dimention_index = 0.000000;		/* Mapped at index 0x608E, subindex 0x00 */
INTEGER8 Homing_method = 0x0;		/* Mapped at index 0x6098, subindex 0x00 */
UNS32 Homing_speeds_Speed_for_switch_search = 0x0;		/* Mapped at index 0x6099, subindex 0x01 */
UNS32 Homing_speeds_Speed_for_zero_search = 0x0;		/* Mapped at index 0x6099, subindex 0x02 */
UNS32 Homing_acceleration = 0x0;		/* Mapped at index 0x609A, subindex 0x00 */
INTEGER16 Current_control_parameter_set_Current_regulator_P_gain = 0x0;		/* Mapped at index 0x60F6, subindex 0x01 */
INTEGER16 Current_control_parameter_set_Current_regulator_I_gain = 0x0;		/* Mapped at index 0x60F6, subindex 0x02 */
INTEGER16 Velocity_control_parameter_set_Velocity_regulator_P_gain = 0x0;		/* Mapped at index 0x60F9, subindex 0x01 */
INTEGER16 Velocity_control_parameter_set_Velocity_regulator_I_gain = 0x0;		/* Mapped at index 0x60F9, subindex 0x02 */
INTEGER16 Position_control_parameter_set_Position_regulator_P_gain = 0x0;		/* Mapped at index 0x60FB, subindex 0x01 */
INTEGER16 Position_control_parameter_set_Position_regulator_I_gain = 0x0;		/* Mapped at index 0x60FB, subindex 0x02 */
INTEGER16 Position_control_parameter_set_Position_regulator_D_gain = 0x0;		/* Mapped at index 0x60FB, subindex 0x03 */
UNS16 Position_control_parameter_set_Velocity_feed_forward_factor = 0x0;		/* Mapped at index 0x60FB, subindex 0x04 */
UNS16 Position_control_parameter_set_Acceleration_feed_forward_factor = 0x0;		/* Mapped at index 0x60FB, subindex 0x05 */
INTEGER32 Target_velocity = 0x0;		/* Mapped at index 0x60FF, subindex 0x00 */
UNS16 Motor_type = 0x0;		/* Mapped at index 0x6402, subindex 0x00 */
UNS16 Motor_data_Continous_current_limit = 0x0;		/* Mapped at index 0x6410, subindex 0x01 */
UNS16 Motor_data_Output_current_limit = 0x0;		/* Mapped at index 0x6410, subindex 0x02 */
UNS8 Motor_data_Pole_pair_number = 0x0;		/* Mapped at index 0x6410, subindex 0x03 */
UNS16 Motor_data_Maximal_speed_in_current_mode = 0x0;		/* Mapped at index 0x6410, subindex 0x04 */
UNS16 Motor_data_Thermal_time_constant_winding = 0x0;		/* Mapped at index 0x6410, subindex 0x05 */
UNS32 Supported_drive_modes = 0x0;		/* Mapped at index 0x6502, subindex 0x00 */

INTEGER32 Set_point = 0x0;		/* Mapped at index 0x60C1, subindex 0x00 */
INTEGER16 VI_Target_velocity = 0x0;		/* Mapped at index 0x6042, subindex 0x00 */
INTEGER16 Targetl_torque = 0x0;		/* Mapped at index 0x6071, subindex 0x00 */
INTEGER32 Pos_actual_value_enc = 0x0;	/* Mapped at index 0x6063, subindex 0x00 */
INTEGER16 Torque_actual_value = 0x0;/* Mapped at index 0x6077, subindex 0x00 */	
/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Ds402_Slave_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Ds402_Slave_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Ds402_Slave_iam_a_slave = 1;

TIMER_HANDLE Ds402_Slave_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Ds402_Slave_obj1000 = 0x22;	/* 34 */
                    subindex Ds402_Slave_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Ds402_Slave_obj1001 = 0x0;	/* 0 */
                    subindex Ds402_Slave_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Ds402_Slave_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex Ds402_Slave_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 Ds402_Slave_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 Ds402_Slave_obj1006 = 0x0;   /* 0 */

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 Ds402_Slave_obj1008[11] = "weiduwulian";
                    subindex Ds402_Slave_Index1008[] = 
                     {
                       { RO, visible_string, 11, (void*)&Ds402_Slave_obj1008, NULL }
                     };

/* index 0x1009 :   Manufacturer Hardware Version. */
                    UNS8 Ds402_Slave_obj1009[10] = "0.2";
                    subindex Ds402_Slave_Index1009[] = 
                     {
                       { RO, visible_string, 10, (void*)&Ds402_Slave_obj1009, NULL }
                     };

/* index 0x100A :   Manufacturer Software Version. */
                    UNS8 Ds402_Slave_obj100A[10] = "0.2";
                    subindex Ds402_Slave_Index100A[] = 
                     {
                       { RO, visible_string, 10, (void*)&Ds402_Slave_obj100A, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 Ds402_Slave_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 Ds402_Slave_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 Ds402_Slave_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 Ds402_Slave_highestSubIndex_obj1016 = 0;
                    UNS32 Ds402_Slave_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 Ds402_Slave_obj1017 = 0x0;   /* 0 */


										
	
/* index 0x1017 :   Mapped variable Position demannd value */ 
                    subindex Ds402_Slave_Index1017[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Ds402_Slave_obj1017, NULL }
                     };											
										
										
										
//										
///* index 0x1018 :   Identity. */
//                    UNS8 Ds402_Slave_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
//                    UNS32 Ds402_Slave_obj1018_Vendor_ID = 0x0;	/* 0 */
//                    UNS32 Ds402_Slave_obj1018_Product_Code = 0x0;	/* 0 */
//                    UNS32 Ds402_Slave_obj1018_Revision_Number = 0x0;	/* 0 */
//                    UNS32 Ds402_Slave_obj1018_Serial_Number = 0x0;	/* 0 */
//                    subindex Ds402_Slave_Index1018[] = 
//                     {
//                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1018, NULL },
//                       { RO, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1018_Vendor_ID, NULL },
//                       { RO, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1018_Product_Code, NULL },
//                       { RO, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1018_Revision_Number, NULL },
//                       { RO, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1018_Serial_Number, NULL }
//                     };

										 
										 
										 
										 
										 
										 
/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x601;	/* 1538 */
                    UNS32 Ds402_Slave_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x581;	/* 1410 */
                    subindex Ds402_Slave_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1400_COB_ID_used_by_PDO = 0x201;	/* 514 */
                    UNS8 Ds402_Slave_obj1400_Transmission_Type = 0xFF;	/* 0 */
                    UNS16 Ds402_Slave_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Ds402_Slave_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1400_SYNC_start_value, NULL }
                     };

										 
	/* index 0x1401 :   Receive PDO 1 Parameter. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1401_COB_ID_used_by_PDO = 0x301;	/* 514 */
                    UNS8 Ds402_Slave_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex Ds402_Slave_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1401_SYNC_start_value, NULL }
                     };
									 
										 
	/* index 0x1402 :   Receive PDO 2 Parameter. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1402_COB_ID_used_by_PDO = 0x401;	/* 514 */
                    UNS8 Ds402_Slave_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex Ds402_Slave_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1402_SYNC_start_value, NULL }
                     };
									 
										 
	/* index 0x1403 :   Receive PDO 3 Parameter. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1403_COB_ID_used_by_PDO = 0x501;	/* 514 */
                    UNS8 Ds402_Slave_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex Ds402_Slave_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1403_SYNC_start_value, NULL }
                     };
									 										 
										 
/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1600[] = 
                    {
											0x60400010,	/*  */
											0x60600008/* */
                    };
                    subindex Ds402_Slave_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1600, NULL },
                       { RW, uint16, sizeof (UNS32), (void*)&Ds402_Slave_obj1600[0], NULL },
											 { RW, uint8, sizeof (UNS32), (void*)&Ds402_Slave_obj1600[1], NULL }
                     };

/* index 0x1601 :   Receive PDO 1 Mapping. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1601 = 2; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1601[] = 
                    {
											0x607A0020,	/*  */
											0x60810020	/*  */
                    };
                    subindex Ds402_Slave_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1601[0], NULL },
											 { RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1601[1], NULL }
                     };										 
										 		

/* index 0x1602 :   Receive PDO 2 Mapping. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1602 = 2; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1602[] = 
                    {
                      //0x60420010,	/*  */
											0x60FF0020/*  */
                    };
                    subindex Ds402_Slave_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1602, NULL },
                       //{ RW, uint16, sizeof (UNS32), (void*)&Ds402_Slave_obj1602[0], NULL },
											 { RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1602[0], NULL }
                     };

/* index 0x1603 :   Receive PDO 3 Mapping. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1603 = 2; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1603[] = 
                    {
											  0x60710010,	/*  */
											  0x60720010	/*  */
                    };
                    subindex Ds402_Slave_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1603, NULL },
                       { RW, uint16, sizeof (UNS32), (void*)&Ds402_Slave_obj1603[0], NULL },
											 { RW, uint16, sizeof (UNS32), (void*)&Ds402_Slave_obj1603[1], NULL }
                     };										 
										 		


/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1800_COB_ID_used_by_PDO = 0x181;	/* 384 */
                    UNS8 Ds402_Slave_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex Ds402_Slave_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1800_SYNC_start_value, NULL }
                     };

										 
/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1801_COB_ID_used_by_PDO = 0x281;	/* 384 */
                    UNS8 Ds402_Slave_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex Ds402_Slave_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1801_SYNC_start_value, NULL }
                     };										 
										 
										 
										 
/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1802_COB_ID_used_by_PDO = 0x381;	/* 384 */
                    UNS8 Ds402_Slave_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex Ds402_Slave_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1802_SYNC_start_value, NULL }
                     };										 
										 
										 
/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1803_COB_ID_used_by_PDO = 0x481;	/* 384 */
                    UNS8 Ds402_Slave_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Ds402_Slave_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 Ds402_Slave_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    subindex Ds402_Slave_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1803, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1803_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1803_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1803_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1803_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Ds402_Slave_obj1803_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_obj1803_SYNC_start_value, NULL }
                     };										 
										 
										 
/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1A00 = 2; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1A00[] = 
                    {
                      0x60410010,	/*  */
                      0x60610008	/*  */
                    };
                    subindex Ds402_Slave_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1A00, NULL },
                       { RW, uint16, sizeof (UNS32), (void*)&Ds402_Slave_obj1A00[0], NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&Ds402_Slave_obj1A00[1], NULL },
                     };

										 														 
/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1A01 = 2; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1A01[] = 
                    {
                      //0x60630020,	/* */
                      0x60640020	/*  */
                    };
                    subindex Ds402_Slave_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1A01[0], NULL }
                       //{ RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1A01[1], NULL }
                     };


/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1A02 = 1; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1A02[] = 
                    {
                      0x606C0020	/*  */
                    };
                    subindex Ds402_Slave_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Ds402_Slave_obj1A02[0], NULL }
                     };


/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 Ds402_Slave_highestSubIndex_obj1A03 = 1; /* number of subindex - 1*/
                    UNS32 Ds402_Slave_obj1A03[] = 
                    {
                        0x60770010	/*  */
                    };
                    subindex Ds402_Slave_Index1A03[] = 
                     {
                        { RW, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj1A03, NULL },
                        { RW, uint16, sizeof (UNS32), (void*)&Ds402_Slave_obj1A03[0], NULL }
                     };

										 
										 
/* index 0x6040 :   Mapped variable Controlword */
                    subindex Ds402_Slave_Index6040[] = 
                     {
                       { RW, uint16, sizeof (INTEGER16), (void*)&Controlword, NULL }
											 //{ RW, uint16, 2, (void*)&Controlword, NULL }
                     };


/* index 0x6060 :   Mapped variable Modes of operation */
                    subindex Ds402_Slave_Index6060[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Modes_of_operation, NULL }
                     };
										 
										 
/* index 0x607A :   Mapped variable Target position */
                    subindex Ds402_Slave_Index607A[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_position, NULL }
                     };										 
										 
										 
				 
/* index 0x60C1 :   Mapped variable set-point */ 
                    subindex Ds402_Slave_Index60C1[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Set_point, NULL }
                     };											 
										 
		

/* index 0x6042 :   Mapped variable VI Target position */ 
                    subindex Ds402_Slave_Index6042[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&VI_Target_velocity, NULL }
                     };											 
										 
										 
/* index 0x60FF :   Mapped variable Target velocity */
                    subindex Ds402_Slave_Index60FF[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_velocity, NULL }
                     };

	

/* index 0x6071 :   Mapped variable Target velocity */ 
                    subindex Ds402_Slave_Index6071[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Targetl_torque, NULL }
                     };


								 
										 
/* index 0x6041 :   Mapped variable Statusword */
                    subindex Ds402_Slave_Index6041[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Statusword, NULL }
                     };


/* index 0x6061 :   Mapped variable Modes of operation display */
                    subindex Ds402_Slave_Index6061[] = 
                     {
                       { RO, int8, sizeof (INTEGER8), (void*)&Modes_of_operation_display, NULL }
                     };
										 
										 
										 
	
/* index 0x6063 :   Mapped variable Position demannd value */ 
                    subindex Ds402_Slave_Index6063[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Pos_actual_value_enc, NULL }
                     };	


										 
/* index 0x6064 :   Mapped variable Position actual value */
                    subindex Ds402_Slave_Index6064[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Position_actual_value, NULL }
                     };

										 
/* index 0x606C :   Mapped variable Velocity actual value */
                    subindex Ds402_Slave_Index606C[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_actual_value, NULL }
                     };
										 
						 
/* index 0x6077 :   Mapped variable Velocity actual value */
                    subindex Ds402_Slave_Index6077[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&Torque_actual_value, NULL }
                     };	

										 
										 

/* index 0x6062 :   Mapped variable Position demannd value */
                    subindex Ds402_Slave_Index6062[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Position_demannd_value, NULL }
                     };



/* index 0x6065 :   Mapped variable Maximal following error */
                    subindex Ds402_Slave_Index6065[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Maximal_following_error, NULL }
                     };

/* index 0x6067 :   Mapped variable Position window */
                    subindex Ds402_Slave_Index6067[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Position_window, NULL }
                     };

/* index 0x6068 :   Mapped variable Position window time */
                    subindex Ds402_Slave_Index6068[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Position_window_time, NULL }
                     };

/* index 0x6069 :   Mapped variable Velocity sensor actual value */
                    subindex Ds402_Slave_Index6069[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_sensor_actual_value, NULL }
                     };

/* index 0x606B :   Mapped variable Velocity demand value */
                    subindex Ds402_Slave_Index606B[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_demand_value, NULL }
                     };



/* index 0x6078 :   Mapped variable Current actual value */
                    subindex Ds402_Slave_Index6078[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&Current_actual_value, NULL }
                     };



/* index 0x607C :   Mapped variable Home offset */
                    subindex Ds402_Slave_Index607C[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Home_offset, NULL }
                     };

/* index 0x607D :   Mapped variable Software position limit */
                    UNS8 Ds402_Slave_highestSubIndex_obj607D = 2; /* number of subindex - 1*/
                    subindex Ds402_Slave_Index607D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj607D, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&Software_position_limit_Minimal_position_limit, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&Software_position_limit_Maximal_position_limit, NULL }
                     };

/* index 0x607F :   Mapped variable Maximal profile velocity */
                    subindex Ds402_Slave_Index607F[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Maximal_profile_velocity, NULL }
                     };

/* index 0x6081 :   Mapped variable Profile velocity */
                    subindex Ds402_Slave_Index6081[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_velocity, NULL }
                     };

/* index 0x6083 :   Mapped variable Profile acceleration */
                    subindex Ds402_Slave_Index6083[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_acceleration, NULL }
                     };

/* index 0x6084 :   Mapped variable Profile deceleration */
                    subindex Ds402_Slave_Index6084[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_deceleration, NULL }
                     };

/* index 0x6085 :   Mapped variable Quick stop deceleration */
                    subindex Ds402_Slave_Index6085[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Quick_stop_deceleration, NULL }
                     };

/* index 0x6086 :   Mapped variable Motion profile type */
                    subindex Ds402_Slave_Index6086[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Motion_profile_type, NULL }
                     };

/* index 0x6089 :   Mapped variable Position notation index */
                    subindex Ds402_Slave_Index6089[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Position_notation_index, NULL }
                     };

/* index 0x608A :   Mapped variable Position dimention index */
                    subindex Ds402_Slave_Index608A[] = 
                     {
                       { RW, real32, sizeof (REAL32), (void*)&Position_dimention_index, NULL }
                     };

/* index 0x608B :   Mapped variable Velocity notation index */
                    subindex Ds402_Slave_Index608B[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Velocity_notation_index, NULL }
                     };

/* index 0x608C :   Mapped variable Velocity dimention index */
                    subindex Ds402_Slave_Index608C[] = 
                     {
                       { RW, real32, sizeof (REAL32), (void*)&Velocity_dimention_index, NULL }
                     };

/* index 0x608D :   Mapped variable Acceleraion notation index */
                    subindex Ds402_Slave_Index608D[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Acceleraion_notation_index, NULL }
                     };

/* index 0x608E :   Mapped variable Acceleraion dimention index */
                    subindex Ds402_Slave_Index608E[] = 
                     {
                       { RW, real32, sizeof (REAL32), (void*)&Acceleraion_dimention_index, NULL }
                     };

/* index 0x6098 :   Mapped variable Homing method */
                    subindex Ds402_Slave_Index6098[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Homing_method, NULL }
                     };

/* index 0x6099 :   Mapped variable Homing speeds */
                    UNS8 Ds402_Slave_highestSubIndex_obj6099 = 2; /* number of subindex - 1*/
                    subindex Ds402_Slave_Index6099[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj6099, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_speeds_Speed_for_switch_search, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_speeds_Speed_for_zero_search, NULL }
                     };

/* index 0x609A :   Mapped variable Homing acceleration */
                    subindex Ds402_Slave_Index609A[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_acceleration, NULL }
                     };

/* index 0x60F6 :   Mapped variable Current control parameter set */
                    UNS8 Ds402_Slave_highestSubIndex_obj60F6 = 2; /* number of subindex - 1*/
                    subindex Ds402_Slave_Index60F6[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj60F6, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Current_control_parameter_set_Current_regulator_P_gain, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Current_control_parameter_set_Current_regulator_I_gain, NULL }
                     };

/* index 0x60F9 :   Mapped variable Velocity control parameter set */
                    UNS8 Ds402_Slave_highestSubIndex_obj60F9 = 2; /* number of subindex - 1*/
                    subindex Ds402_Slave_Index60F9[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj60F9, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Velocity_control_parameter_set_Velocity_regulator_P_gain, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Velocity_control_parameter_set_Velocity_regulator_I_gain, NULL }
                     };

/* index 0x60FB :   Mapped variable Position control parameter set */
                    UNS8 Ds402_Slave_highestSubIndex_obj60FB = 5; /* number of subindex - 1*/
                    subindex Ds402_Slave_Index60FB[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj60FB, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Position_control_parameter_set_Position_regulator_P_gain, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Position_control_parameter_set_Position_regulator_I_gain, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Position_control_parameter_set_Position_regulator_D_gain, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Position_control_parameter_set_Velocity_feed_forward_factor, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Position_control_parameter_set_Acceleration_feed_forward_factor, NULL }
                     };



/* index 0x6402 :   Mapped variable Motor type */
                    subindex Ds402_Slave_Index6402[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_type, NULL }
                     };

/* index 0x6410 :   Mapped variable Motor data */
                    UNS8 Ds402_Slave_highestSubIndex_obj6410 = 5; /* number of subindex - 1*/
                    subindex Ds402_Slave_Index6410[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Ds402_Slave_highestSubIndex_obj6410, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Continous_current_limit, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Output_current_limit, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_data_Pole_pair_number, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Maximal_speed_in_current_mode, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Thermal_time_constant_winding, NULL }
                     };

/* index 0x6502 :   Mapped variable Supported drive modes */
                    subindex Ds402_Slave_Index6502[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Supported_drive_modes, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Ds402_Slave_objdict[] = 
{
  { (subindex*)Ds402_Slave_Index1000,sizeof(Ds402_Slave_Index1000)/sizeof(Ds402_Slave_Index1000[0]), 0x1000},
  { (subindex*)Ds402_Slave_Index1001,sizeof(Ds402_Slave_Index1001)/sizeof(Ds402_Slave_Index1001[0]), 0x1001},
  { (subindex*)Ds402_Slave_Index1008,sizeof(Ds402_Slave_Index1008)/sizeof(Ds402_Slave_Index1008[0]), 0x1008},
  { (subindex*)Ds402_Slave_Index1009,sizeof(Ds402_Slave_Index1009)/sizeof(Ds402_Slave_Index1009[0]), 0x1009},
  { (subindex*)Ds402_Slave_Index100A,sizeof(Ds402_Slave_Index100A)/sizeof(Ds402_Slave_Index100A[0]), 0x100A},
  { (subindex*)Ds402_Slave_Index1017,sizeof(Ds402_Slave_Index1017)/sizeof(Ds402_Slave_Index1017[0]), 0x1017},
  { (subindex*)Ds402_Slave_Index1200,sizeof(Ds402_Slave_Index1200)/sizeof(Ds402_Slave_Index1200[0]), 0x1200},
  { (subindex*)Ds402_Slave_Index1400,sizeof(Ds402_Slave_Index1400)/sizeof(Ds402_Slave_Index1400[0]), 0x1400}, 
  { (subindex*)Ds402_Slave_Index1401,sizeof(Ds402_Slave_Index1401)/sizeof(Ds402_Slave_Index1401[0]), 0x1401},	 
	{ (subindex*)Ds402_Slave_Index1402,sizeof(Ds402_Slave_Index1402)/sizeof(Ds402_Slave_Index1402[0]), 0x1402},
  { (subindex*)Ds402_Slave_Index1403,sizeof(Ds402_Slave_Index1403)/sizeof(Ds402_Slave_Index1403[0]), 0x1403},	
  { (subindex*)Ds402_Slave_Index1600,sizeof(Ds402_Slave_Index1600)/sizeof(Ds402_Slave_Index1600[0]), 0x1600}, 
  { (subindex*)Ds402_Slave_Index1601,sizeof(Ds402_Slave_Index1601)/sizeof(Ds402_Slave_Index1601[0]), 0x1601},	
	{ (subindex*)Ds402_Slave_Index1602,sizeof(Ds402_Slave_Index1602)/sizeof(Ds402_Slave_Index1602[0]), 0x1602},
  { (subindex*)Ds402_Slave_Index1603,sizeof(Ds402_Slave_Index1603)/sizeof(Ds402_Slave_Index1603[0]), 0x1603},
  { (subindex*)Ds402_Slave_Index1800,sizeof(Ds402_Slave_Index1800)/sizeof(Ds402_Slave_Index1800[0]), 0x1800}, 
  { (subindex*)Ds402_Slave_Index1801,sizeof(Ds402_Slave_Index1801)/sizeof(Ds402_Slave_Index1801[0]), 0x1801},	
  { (subindex*)Ds402_Slave_Index1802,sizeof(Ds402_Slave_Index1802)/sizeof(Ds402_Slave_Index1802[0]), 0x1802},	
  { (subindex*)Ds402_Slave_Index1803,sizeof(Ds402_Slave_Index1803)/sizeof(Ds402_Slave_Index1803[0]), 0x1803},	
  { (subindex*)Ds402_Slave_Index1A00,sizeof(Ds402_Slave_Index1A00)/sizeof(Ds402_Slave_Index1A00[0]), 0x1A00},
  { (subindex*)Ds402_Slave_Index1A01,sizeof(Ds402_Slave_Index1A01)/sizeof(Ds402_Slave_Index1A01[0]), 0x1A01},	
  { (subindex*)Ds402_Slave_Index1A02,sizeof(Ds402_Slave_Index1A02)/sizeof(Ds402_Slave_Index1A02[0]), 0x1A02},	
  { (subindex*)Ds402_Slave_Index1A03,sizeof(Ds402_Slave_Index1A03)/sizeof(Ds402_Slave_Index1A03[0]), 0x1A03},	
  { (subindex*)Ds402_Slave_Index6040,sizeof(Ds402_Slave_Index6040)/sizeof(Ds402_Slave_Index6040[0]), 0x6040},
  { (subindex*)Ds402_Slave_Index6041,sizeof(Ds402_Slave_Index6041)/sizeof(Ds402_Slave_Index6041[0]), 0x6041},
  { (subindex*)Ds402_Slave_Index6060,sizeof(Ds402_Slave_Index6060)/sizeof(Ds402_Slave_Index6060[0]), 0x6060},
  { (subindex*)Ds402_Slave_Index6061,sizeof(Ds402_Slave_Index6061)/sizeof(Ds402_Slave_Index6061[0]), 0x6061},
  { (subindex*)Ds402_Slave_Index6062,sizeof(Ds402_Slave_Index6062)/sizeof(Ds402_Slave_Index6062[0]), 0x6062},
  { (subindex*)Ds402_Slave_Index6064,sizeof(Ds402_Slave_Index6064)/sizeof(Ds402_Slave_Index6064[0]), 0x6064},
  { (subindex*)Ds402_Slave_Index6065,sizeof(Ds402_Slave_Index6065)/sizeof(Ds402_Slave_Index6065[0]), 0x6065},
  { (subindex*)Ds402_Slave_Index6067,sizeof(Ds402_Slave_Index6067)/sizeof(Ds402_Slave_Index6067[0]), 0x6067},
  { (subindex*)Ds402_Slave_Index6068,sizeof(Ds402_Slave_Index6068)/sizeof(Ds402_Slave_Index6068[0]), 0x6068},
  { (subindex*)Ds402_Slave_Index6069,sizeof(Ds402_Slave_Index6069)/sizeof(Ds402_Slave_Index6069[0]), 0x6069},
  { (subindex*)Ds402_Slave_Index606B,sizeof(Ds402_Slave_Index606B)/sizeof(Ds402_Slave_Index606B[0]), 0x606B},
  { (subindex*)Ds402_Slave_Index606C,sizeof(Ds402_Slave_Index606C)/sizeof(Ds402_Slave_Index606C[0]), 0x606C},
  { (subindex*)Ds402_Slave_Index6078,sizeof(Ds402_Slave_Index6078)/sizeof(Ds402_Slave_Index6078[0]), 0x6078},
  { (subindex*)Ds402_Slave_Index607A,sizeof(Ds402_Slave_Index607A)/sizeof(Ds402_Slave_Index607A[0]), 0x607A},
  { (subindex*)Ds402_Slave_Index607C,sizeof(Ds402_Slave_Index607C)/sizeof(Ds402_Slave_Index607C[0]), 0x607C},
  { (subindex*)Ds402_Slave_Index607D,sizeof(Ds402_Slave_Index607D)/sizeof(Ds402_Slave_Index607D[0]), 0x607D},
  { (subindex*)Ds402_Slave_Index607F,sizeof(Ds402_Slave_Index607F)/sizeof(Ds402_Slave_Index607F[0]), 0x607F},
  { (subindex*)Ds402_Slave_Index6081,sizeof(Ds402_Slave_Index6081)/sizeof(Ds402_Slave_Index6081[0]), 0x6081},
  { (subindex*)Ds402_Slave_Index6083,sizeof(Ds402_Slave_Index6083)/sizeof(Ds402_Slave_Index6083[0]), 0x6083},
  { (subindex*)Ds402_Slave_Index6084,sizeof(Ds402_Slave_Index6084)/sizeof(Ds402_Slave_Index6084[0]), 0x6084},
  { (subindex*)Ds402_Slave_Index6085,sizeof(Ds402_Slave_Index6085)/sizeof(Ds402_Slave_Index6085[0]), 0x6085},
  { (subindex*)Ds402_Slave_Index6086,sizeof(Ds402_Slave_Index6086)/sizeof(Ds402_Slave_Index6086[0]), 0x6086},
  { (subindex*)Ds402_Slave_Index6089,sizeof(Ds402_Slave_Index6089)/sizeof(Ds402_Slave_Index6089[0]), 0x6089},
  { (subindex*)Ds402_Slave_Index608A,sizeof(Ds402_Slave_Index608A)/sizeof(Ds402_Slave_Index608A[0]), 0x608A},
  { (subindex*)Ds402_Slave_Index608B,sizeof(Ds402_Slave_Index608B)/sizeof(Ds402_Slave_Index608B[0]), 0x608B},
  { (subindex*)Ds402_Slave_Index608C,sizeof(Ds402_Slave_Index608C)/sizeof(Ds402_Slave_Index608C[0]), 0x608C},
  { (subindex*)Ds402_Slave_Index608D,sizeof(Ds402_Slave_Index608D)/sizeof(Ds402_Slave_Index608D[0]), 0x608D},
  { (subindex*)Ds402_Slave_Index608E,sizeof(Ds402_Slave_Index608E)/sizeof(Ds402_Slave_Index608E[0]), 0x608E},
  { (subindex*)Ds402_Slave_Index6098,sizeof(Ds402_Slave_Index6098)/sizeof(Ds402_Slave_Index6098[0]), 0x6098},
  { (subindex*)Ds402_Slave_Index6099,sizeof(Ds402_Slave_Index6099)/sizeof(Ds402_Slave_Index6099[0]), 0x6099},
  { (subindex*)Ds402_Slave_Index609A,sizeof(Ds402_Slave_Index609A)/sizeof(Ds402_Slave_Index609A[0]), 0x609A},
  { (subindex*)Ds402_Slave_Index60F6,sizeof(Ds402_Slave_Index60F6)/sizeof(Ds402_Slave_Index60F6[0]), 0x60F6},
  { (subindex*)Ds402_Slave_Index60F9,sizeof(Ds402_Slave_Index60F9)/sizeof(Ds402_Slave_Index60F9[0]), 0x60F9},
  { (subindex*)Ds402_Slave_Index60FB,sizeof(Ds402_Slave_Index60FB)/sizeof(Ds402_Slave_Index60FB[0]), 0x60FB},
  { (subindex*)Ds402_Slave_Index60FF,sizeof(Ds402_Slave_Index60FF)/sizeof(Ds402_Slave_Index60FF[0]), 0x60FF},
  { (subindex*)Ds402_Slave_Index6402,sizeof(Ds402_Slave_Index6402)/sizeof(Ds402_Slave_Index6402[0]), 0x6402},
  { (subindex*)Ds402_Slave_Index6410,sizeof(Ds402_Slave_Index6410)/sizeof(Ds402_Slave_Index6410[0]), 0x6410},
  { (subindex*)Ds402_Slave_Index6502,sizeof(Ds402_Slave_Index6502)/sizeof(Ds402_Slave_Index6502[0]), 0x6502},
  { (subindex*)Ds402_Slave_Index60C1,sizeof(Ds402_Slave_Index60C1)/sizeof(Ds402_Slave_Index60C1[0]), 0x60C1},	
  { (subindex*)Ds402_Slave_Index6042,sizeof(Ds402_Slave_Index6042)/sizeof(Ds402_Slave_Index6042[0]), 0x6042},	
  { (subindex*)Ds402_Slave_Index6071,sizeof(Ds402_Slave_Index6071)/sizeof(Ds402_Slave_Index6071[0]), 0x6071},	
  { (subindex*)Ds402_Slave_Index6063,sizeof(Ds402_Slave_Index6063)/sizeof(Ds402_Slave_Index6063[0]), 0x6063},	
  { (subindex*)Ds402_Slave_Index6077,sizeof(Ds402_Slave_Index6077)/sizeof(Ds402_Slave_Index6077[0]), 0x6077},		
	
};

const indextable * Ds402_Slave_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
  int i;
  (void)d;
  switch(wIndex){
   case 0x1000: i = 0;break;
   case 0x1001: i = 1;break;
   case 0x1008: i = 2;break;
   case 0x1009: i = 3;break;
   case 0x100A: i = 4;break;
   case 0x1017: i = 5;break;
   case 0x1200: i = 6;break;
   case 0x1400: i = 7;break;
	 case 0x1401: i = 8;break;
	 case 0x1402: i = 9;break;
	 case 0x1403: i = 10;break;
   case 0x1600: i = 11;break;
   case 0x1601: i = 12;break;
	 case 0x1602: i = 13;break;
   case 0x1603: i = 14;break;
   case 0x1800: i = 15;break;
	 case 0x1801: i = 16;break;
	 case 0x1802: i = 17;break;
	 case 0x1803: i = 18;break;
   case 0x1A00: i = 19;break;
	 case 0x1A01: i = 20;break;
	 case 0x1A02: i = 21;break;
	 case 0x1A03: i = 22;break;
   case 0x6040: i = 23;break;
   case 0x6041: i = 24;break;
   case 0x6060: i = 25;break;
   case 0x6061: i = 26;break;
   case 0x6062: i = 27;break;
   case 0x6064: i = 28;break;
   case 0x6065: i = 29;break;
   case 0x6067: i = 30;break;
   case 0x6068: i = 31;break;
   case 0x6069: i = 32;break;
   case 0x606B: i = 33;break;
   case 0x606C: i = 34;break;
   case 0x6078: i = 35;break;
   case 0x607A: i = 36;break;
   case 0x607C: i = 37;break;
   case 0x607D: i = 38;break;
   case 0x607F: i = 39;break;
   case 0x6081: i = 40;break;
   case 0x6083: i = 41;break;
   case 0x6084: i = 42;break;
   case 0x6085: i = 43;break;
   case 0x6086: i = 44;break;
   case 0x6089: i = 45;break;
   case 0x608A: i = 46;break;
   case 0x608B: i = 47;break;
   case 0x608C: i = 48;break;
   case 0x608D: i = 49;break;
   case 0x608E: i = 50;break;
   case 0x6098: i = 51;break;
   case 0x6099: i = 52;break;
   case 0x609A: i = 53;break;
   case 0x60F6: i = 54;break;
   case 0x60F9: i = 55;break;
   case 0x60FB: i = 56;break;
   case 0x60FF: i = 57;break;
   case 0x6402: i = 58;break;
   case 0x6410: i = 59;break;
   case 0x6502: i = 60;break;
   case 0x60C1: i = 61;break;
   case 0x6042: i = 62;break;
   case 0x6071: i = 63;break;
   case 0x6063: i = 64;break;
   case 0x6077: i = 65;break;	
   default:
        *errorCode = OD_NO_SUCH_OBJECT;
        return NULL;
  }
  *errorCode = OD_SUCCESSFUL;
  return &Ds402_Slave_objdict[i];
}

/*get object offset*/
unsigned int ObScanIndex(UNS16 wIndex)
{
  unsigned int i = 0;
  switch(wIndex){
   case 0x1000: i = 0;break;
   case 0x1001: i = 1;break;
   case 0x1008: i = 2;break;
   case 0x1009: i = 3;break;
   case 0x100A: i = 4;break;
   case 0x1017: i = 5;break;
   case 0x1200: i = 6;break;
   case 0x1400: i = 7;break;
	 case 0x1401: i = 8;break;
	 case 0x1402: i = 9;break;
	 case 0x1403: i = 10;break;
   case 0x1600: i = 11;break;
   case 0x1601: i = 12;break;
	 case 0x1602: i = 13;break;
   case 0x1603: i = 14;break;
   case 0x1800: i = 15;break;
	 case 0x1801: i = 16;break;
	 case 0x1802: i = 17;break;
	 case 0x1803: i = 18;break;
   case 0x1A00: i = 19;break;
	 case 0x1A01: i = 20;break;
	 case 0x1A02: i = 21;break;
	 case 0x1A03: i = 22;break;
   case 0x6040: i = 23;break;
   case 0x6041: i = 24;break;
   case 0x6060: i = 25;break;
   case 0x6061: i = 26;break;
   case 0x6062: i = 27;break;
   case 0x6064: i = 28;break;
   case 0x6065: i = 29;break;
   case 0x6067: i = 30;break;
   case 0x6068: i = 31;break;
   case 0x6069: i = 32;break;
   case 0x606B: i = 33;break;
   case 0x606C: i = 34;break;
   case 0x6078: i = 35;break;
   case 0x607A: i = 36;break;
   case 0x607C: i = 37;break;
   case 0x607D: i = 38;break;
   case 0x607F: i = 39;break;
   case 0x6081: i = 40;break;
   case 0x6083: i = 41;break;
   case 0x6084: i = 42;break;
   case 0x6085: i = 43;break;
   case 0x6086: i = 44;break;
   case 0x6089: i = 45;break;
   case 0x608A: i = 46;break;
   case 0x608B: i = 47;break;
   case 0x608C: i = 48;break;
   case 0x608D: i = 49;break;
   case 0x608E: i = 50;break;
   case 0x6098: i = 51;break;
   case 0x6099: i = 52;break;
   case 0x609A: i = 53;break;
   case 0x60F6: i = 54;break;
   case 0x60F9: i = 55;break;
   case 0x60FB: i = 56;break;
   case 0x60FF: i = 57;break;
   case 0x6402: i = 58;break;
   case 0x6410: i = 59;break;
   case 0x6502: i = 60;break;
   case 0x60C1: i = 61;break;
   case 0x6042: i = 62;break;
   case 0x6071: i = 63;break;
   case 0x6063: i = 64;break;
   case 0x6077: i = 65;break;	 	
   default:
        //add some check code;
        break;
  }
  return i;
}


/*get object data by type*/
UNS32 ObGetDataByType(UNS8 dataType, void * data)
{
    switch (dataType) {
        case  int8:     return (UNS32)(*(int8_t*)data);
        case  int16:    return (UNS32)(*(int16_t*)data);
        case  int32:    return (UNS32)(*(int32_t*)data);
        case  uint8:    return (UNS32)(*(uint8_t*)data);
        case  uint16:   return (UNS32)(*(uint16_t*)data);
        case  uint32:   return (UNS32)(*(uint32_t*)data);
        case  real32:   return (UNS32)(*(uint32_t*)data);
    };
		return 0;
}
/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Ds402_Slave_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index Ds402_Slave_firstIndex = {
  6, /* SDO_SVR */
  0, /* SDO_CLT */
  7, /* PDO_RCV */      //0x1400
  11, /* PDO_RCV_MAP */ //0x1600µÄÎ»ÖÃ 
  15, /* PDO_TRS */
  19 /* PDO_TRS_MAP */
};

const quick_index Ds402_Slave_lastIndex = {
  6, /* SDO_SVR */
  0, /* SDO_CLT */
  10, /* PDO_RCV */    // 0x1403
  14, /* PDO_RCV_MAP */   //1603
  18, /* PDO_TRS */ 
  22 /* PDO_TRS_MAP */
};
const UNS16 Ds402_Slave_ObjdictSize = sizeof(Ds402_Slave_objdict)/sizeof(Ds402_Slave_objdict[0]); 
CO_Data Ds402_Slave_Data = CANOPEN_NODE_DATA_INITIALIZER(Ds402_Slave);


